server:
  port: 8082

spring:
  application:
    name: catalogo
  data:
    mongodb:
      # URI estándar. MongoDB crea la BD automáticamente si no existe.
      uri: mongodb://localhost:27017/catalogo_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # Importante para evitar errores de DNS

# Clave secreta compartida
app:
  jwt:
    secret: "bXN1cGVyc2VjcmV0a2V5Zm9ydGhlc3RvcmUxMjM0NVhZWlo="